
package com.swirepay.android_sdk.checkout.exception;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/**
 * Exception generated by the Checkout components to indicate an error.
 * Usually related to an implementation error.
 */
public class CheckoutException extends RuntimeException {

    private static final long serialVersionUID = -2465223452079546925L;

    public CheckoutException(@NonNull String errorMessage) {
        this(errorMessage, null);
    }

    public CheckoutException(@NonNull String errorMessage, @Nullable Throwable cause) {
        super(errorMessage, cause);
    }
}
